### ISSUE TITLE
Ask for why should sleep before close dataconn

### ISSUE THREAD

**Issue by mohanson** [yob/graval#15]
https://github.com/yob/graval/blob/20ac9ad57642da3f8eb3f1b9b334aed8b20f021d/ftpconn.go#L205

I don't understand what is the meaning here, if not sleeping, the client will receive less data?

**Comment by yob** [comment]
Good question, and I'm not sure what the answer is.

That comment was from a commit by someone who's run this in production more than me and has no doubt run into some compatibility issues. 

https://github.com/yob/graval/commit/dbb3278940364fe079dc9d40f15c741a367a5a59

I can't say if this line is still needed or not, sorry!

**Comment by mohanson** [comment]
This is really weird, thanks!
